### ISSUE TITLE
DIFI Blocks documentation not showing up in docs tab

### ISSUE THREAD

**Issue by 777arc** [microsoft/azure-software-radio#52]
Python block's docs look fine but the C++ blocks (currently just the 2 DIFI blocks) don't have their docstrings showing up in GRC in the documentation tab.  Seems like the docs are in the right spot in the header file, using the proper doxygen tags, so might be a cmake issue?  Both the dev VM and my local install demonstrate this issue.

![image](https://user-images.githubusercontent.com/5722532/153969294-9efdf097-8111-44a3-ba36-53eb6e29e785.png)

[AB#10543](https://ag-ascii.visualstudio.com/a2b18d2f-d51c-4194-97e8-d6244d4a0156/_workitems/edit/10543)

**Comment by jo-rivera** [comment]
Thanks @777arc for pointing out this issue. I'm able to replicate it in the dev VM environment.
